

Table config.api_constraints {
    id uint [pk, not null, unique]
    platform_name vico.platform_name [not null]
    quota_limit uint
    quota_reset_cron varchar(31) [not null]
    quota_left int
    reported datetime
    rate_limit_per_minute int
    metadata_stale_days int
}

