Table vico.user{
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    email varchar(255) [not null, unique]
    password_hash varchar(255) [not null]
    created datetime
}

Table vico.curator{
    id uint [pk, not null, unique]
    user_id uint [not null, ref: > vico.user.id]
    curator_role_id uint [not null, ref: > vico.curator_role.id]
    collection_id uint [not null, ref: > vico.collection.id]
}

Table vico.curator_role{
    id uint [pk, not null, unique]
    name vico.role_name
    description text
}

enum vico.role_name {
    owner
    moderator
    contributor
}

Table vico.subscription{
    id uint [pk, not null, unique]
    user_id uint [not null, ref: > vico.user.id]
    collection_id uint [not null, ref: > vico.collection.id]
    since datetime 

    Indexes {
            (user_id, collection_id) [unique] 
        }
}



Table vico.collection{
    id uint [pk, not null, unique]
    name varchar(127) [not null]
    description text
    created datetime [not null]
    updated datetime
    public bool [not null, default: 0]
    thumbnail_path varchar(511)
}


Table vico.collection_classification{
    id uint [pk, not null, unique]
    collection_id uint [not null, ref: > vico.collection.id]
    subcategory_id uint [not null, ref: > vico.subcategory.id]
}


Table vico.category{
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    description text
}

Table vico.subcategory{
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    description text
    category_id uint [not null, ref: > vico.category.id]
}


Table vico.channel{
    id uint [pk, not null, unique]
    metadata_date datetime [not null]
    platform platform_name
    platform_channel_id varchar(255) [not null]
    name varchar(127) [not null]
    thumbnail_url varchar(511)
    created datetime
    indexes {
        (platform, platform_channel_id) [unique]
        }
}

enum platform_name {
    youtube
}

Table vico.video{
    id uint [pk, not null, unique]
    metadata_date datetime [not null]
    channel_id uint [not null, ref: > vico.channel.id]
    platform_video_id varchar(255) [not null]
    title varchar(127)
    description text
    type_id uint [not null, ref: > vico.video_type.id]
    thumbnail_url varchar(511)
    created datetime
    updated datetime
    duration uint
}

Table vico.video_type{
    id uint [pk, not null, unique]
    name video_types [default: `video`]
}

enum video_types{
    short
    video
    "live-stream"
    vod
}


Table vico.collection_filter{
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    description text
    pattern text
    collection_id uint [not null, ref: > vico.collection.id]
    channel_id uint [not null, ref: > vico.channel.id]
    created datetime
}


Table vico.collection_items{ // gefiltert oder manuell hinzugefuegt.
    id uint [pk, not null, unique]
    curator_id uint [ref: > vico.curator.id]
    filter_id uint [ref: > vico.collection_filter.id]
    collection_id uint [not null, ref: > vico.collection.id]
    added datetime
    video_id uint [not null, ref: > vico.video.id]
}


Table vico.collection_report{
    id uint [pk, not null, unique]
    reported_by uint [not null, ref: > vico.user.id]
    reported_at datetime
    collection_id uint [not null, ref: > vico.collection.id]
    message varchar(511)
    reason_id uint [not null, ref: > vico.report_reason.id]
    status report_status [default: "pending"]
    updated datetime
    resolved_at datetime
}

Table vico.report_reason{
    id uint [pk, not null, unique]
    name report_reason
    description text

}

Enum report_reason{
    copyright
    spam
    inappropriate
    wrong_category
    harassment
}

Enum report_status{
    pending
    reviewed
    dismissed
    action_taken
}