Table vico.user{
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    email varchar(255) [not null, unique]
    password_hash varchar(255) [not null]
    created datetime
}

Table vico.membership{
    id uint [pk, not null, unique]
    user_id uint [not null, ref: > vico.user.id]
    member_role_id uint [not null, ref: > vico.member_role.id]
    collection_id uint [not null, ref: > vico.collection.id]
    since datetime
    notify bool [default:1]
    last_viewed datetime
    priority uint [not null, default: 0]
    sort_index uint [not null, default: 0]

    indexes { 
        (user_id, priority, sort_index)
        (user_id, collection_id) [unique] 
    }

}

Table vico.member_role{
    id uint [pk, not null, unique]
    name vico.role_name
    description text
}

enum vico.role_name {
    owner
    moderator
    contributor
    subscriber
}



Table vico.collection{
    id uint [pk, not null, unique]
    name varchar(127) [not null]
    description text
    created datetime [not null]
    updated datetime
    public bool [not null, default: 0]
    thumbnail_path varchar(511)
}


Table vico.collection_classification{
    id uint [pk, not null, unique]
    collection_id uint [not null, ref: > vico.collection.id]
    subcategory_id uint [not null, ref: > vico.subcategory.id]
}


Table vico.category{
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    description text
}

Table vico.subcategory{
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    description text
    category_id uint [not null, ref: > vico.category.id]
}


Table vico.channel{
    id uint [pk, not null, unique]
    metadata_date datetime [not null]
    platform platform_name
    platform_channel_id varchar(255) [not null]
    name varchar(127) [not null]
    thumbnail_url varchar(511)
    created datetime
    indexes {
        (platform, platform_channel_id) [unique]
        }
}

enum platform_name {
    youtube
}

Table vico.video{
    id uint [pk, not null, unique]
    metadata_date datetime [not null]
    channel_id uint [not null, ref: > vico.channel.id]
    platform_video_id varchar(255) [not null]
    applied_by_filter_id uint [ref: > vico.collection_filter.id]
    title varchar(127)
    description text
    type_id uint [not null, ref: > vico.video_type.id]
    thumbnail_url varchar(511)
    created datetime
    updated datetime
    duration uint
}

Table vico.video_type{
    id uint [pk, not null, unique]
    name video_types [default: `video`]
}

enum video_types{
    short
    video
    "live-stream"
    vod
}



Table vico.collection_filter{ // Filter der generell einer Kollektion zugehoehrt. Ob kollektionsweit oder per channel gefiltert wird ist abhaengig vom zustand des datensatzes 
    id uint [pk, not null, unique]
    name varchar(63) [not null]
    description text
    pattern text
    collection_id uint [not null, ref: > vico.collection.id]
    channel_id uint [ref: > vico.channel.id]
    target_scope filter_scopes [default: "global", not null] // global=kollektionsweit
    created datetime
}

Enum filter_scopes{
    global
    channel
}


Table vico.collection_item{ // gefiltert oder manuell hinzugefuegt.
    id uint [pk, not null, unique]
    membership_id uint [ref: > vico.membership.id]
    filter_id uint [ref: > vico.collection_filter.id]
    collection_id uint [not null, ref: > vico.collection.id]
    added datetime
    video_id uint [not null, ref: > vico.video.id]
    priority uint [not null, default: 0]
    sort_index uint [not null, default: 0]

    indexes { 
        (collection_id, priority, sort_index)
    }

}


Table vico.collection_report{
    id uint [pk, not null, unique]
    reported_by uint [not null, ref: > vico.user.id]
    reported_at datetime
    collection_id uint [not null, ref: > vico.collection.id]
    message varchar(511)
    reason_id uint [not null, ref: > vico.report_reason.id]
    status report_status [default: "pending"]
    updated datetime
    resolved_at datetime
}

Table vico.report_reason{
    id uint [pk, not null, unique]
    name report_reason
    description text

}

Enum report_reason{
    copyright
    spam
    inappropriate
    wrong_category
    harassment
}

Enum report_status{
    pending
    reviewed
    dismissed
    action_taken
}

Table vico.feedback{
    id uint [pk, unique, not null]
    most_wanted_id unint [ref: > vico.most_wanted.id]
    message varchar(511)
    reported datetime [not null]
    user_id uint [ref: > vico.user.id]
}

Table vico.most_wanted{
    id uint [pk, unique, not null]
    feature_name varchar(63)
    description text
}